DROP TABLE IF EXISTS url_checks;
DROP TABLE IF EXISTS urls;

CREATE TABLE urls (
                      id BIGINT generated by default as identity not null,
                      name VARCHAR(500),
                      created_at TIMESTAMP DEFAULT NOW(),
                      constraint pk_url primary key (id)
);

CREATE TABLE url_checks (
                            id BIGINT generated by default as identity not null,
                            url_id BIGINT REFERENCES urls(id) NOT NULL,
                            status_code INT,
                            h1 VARCHAR(500),
                            title VARCHAR(500),
                            description text,
                            created_at TIMESTAMP DEFAULT NOW(),
                            constraint pk_url_check primary key (id)
);